# Matrices

## Init

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [7]:
rng = np.random.default_rng()
def random_2d_array(N, M):
  return rng.integers(low=0, high=9, size=(N,M))

## Exercises

### 1.
The goal of this exercise is to create a matrix that contains
the dot products between all pairs of columns in two other
matrices. First, create two 4x2 matrices (that is, 4 rows, 2
columns) of random numbers. Then write a double-for loop
in which you compute the dot products between each column
of both matrices. The i, j element of the resulting matrix will
be the dot product between column i of the first matrix and
column j of the second matrix.

In [27]:
N, M = 4, 2
A = random_2d_array(N, M)
B = random_2d_array(N, M)
C = np.zeros((M, M))
for i in range(M):
  for j in range(M):
    C[i, j] = np.dot(A[:, i], B[:, j])

C

array([[58., 71.],
       [38., 35.]])

### 2.
Create a symmetric matrix by starting with a dense random
numbers matrix and applying three matrix operations: convert
to triangular, transpose, matrix addition.

In [23]:
A = random_2d_array(3, 3)
print(A)
A = np.tril(A)
print(A)
A += np.transpose(A)
A

[[6 3 7]
 [8 6 5]
 [3 5 0]]
[[6 0 0]
 [8 6 0]
 [3 5 0]]


array([[12,  8,  3],
       [ 8, 12,  5],
       [ 3,  5,  0]])

### 3.
Create a diagonal matrix of size 4x8 without using the diag()
function. The diagonal elements should be 1,2,3,4. How much
of your code would you need to change to create an 8x4 diagonal
matrix?

In [25]:
A = np.zeros((4, 8))
for i in range(min(A.shape)):
  A[i, i] = i+1
A

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0.]])